package com.handge.housingfund.database.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

/**
 * HHousingCoborrowerExtension generated by hbm2java
 */
@Entity
@Table(name = "c_loan_housing_coborrower_extension")
@org.hibernate.annotations.Table(appliesTo = "c_loan_housing_coborrower_extension", comment = "共同借款人拓展表")
public class CLoanHousingCoborrowerExtension extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 7108522905394306884L;

	@Column(name = "JCD", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '缴存地'")
	private String jcd;
	@Column(name = "HKSZD", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '户口所在地'")
	private String hkszd;
	@Column(name = "JZNY", columnDefinition = "VARCHAR(6) DEFAULT NULL COMMENT '缴至年月'")
	private String jzny;
	@Column(name = "GRZHZT", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '个人账户状态'")
	private String grzhzt;
	@Column(name = "LXZCJCYS", columnDefinition = "NUMERIC(4,0) DEFAULT NULL COMMENT '连续正常缴存月数'")
	private BigDecimal lxzcjcys = BigDecimal.ZERO;
	@Column(name = "YJCE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '月缴存额'")
	private BigDecimal yjce = BigDecimal.ZERO;
	@Column(name = "GRJCJS", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '个人缴存基数'")
	private BigDecimal grjcjs = BigDecimal.ZERO;
	@Column(name = "GRZHYE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '个人账户余额'")
	private BigDecimal grzhye = BigDecimal.ZERO;
	@Column(name = "DWMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '单位名称'")
	private String dwmc;
	@Column(name = "DWZH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '单位账号'")
	private String dwzh;
	@Column(name = "DWDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '单位电话'")
	private String dwdh;
	@Column(name = "DWXZ", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '单位性质'")
	private String dwxz;
	@Column(name = "DWDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '单位地址'")
	private String dwdz;
	@Column(name = "YWLSH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '业务流水号'")
	private String ywlsh;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;

	public String getBlzl() {
		return blzl;
	}

	public void setBlzl(String blzl) {
		this.blzl = blzl;
	}

	public CLoanHousingCoborrowerExtension() {
	}

	public CLoanHousingCoborrowerExtension(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted, String jcd, String hkszd, String jzny, String grzhzt,
										   BigDecimal lxzcjcys, BigDecimal yjce, BigDecimal grjcjs, BigDecimal grzhye, String dwmc, String dwzh,
										   String dwdh, String dwxz, String dwdz, String ywlsh, String blzl) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.jcd = jcd;
		this.hkszd = hkszd;
		this.jzny = jzny;
		this.grzhzt = grzhzt;
		this.lxzcjcys = lxzcjcys;
		this.yjce = yjce;
		this.grjcjs = grjcjs;
		this.grzhye = grzhye;
		this.dwmc = dwmc;
		this.dwzh = dwzh;
		this.dwdh = dwdh;
		this.dwxz = dwxz;
		this.dwdz = dwdz;
		this.ywlsh = ywlsh;
		this.blzl = blzl;
	}

	public String getJcd() {
		return this.jcd;
	}

	public void setJcd(String jcd) {
		this.jcd = jcd;
	}

	public String getHkszd() {
		return this.hkszd;
	}

	public void setHkszd(String hkszd) {
		this.hkszd = hkszd;
	}

	public String getJzny() {
		return this.jzny;
	}

	public void setJzny(String jzny) {
		this.jzny = jzny;
	}

	public BigDecimal getLxzcjcys() {
		return this.lxzcjcys;
	}

	public void setLxzcjcys(BigDecimal lxzcjcys) {
		this.lxzcjcys = lxzcjcys;
	}

	public BigDecimal getYjce() {
		return this.yjce;
	}

	public void setYjce(BigDecimal yjce) {
		this.yjce = yjce;
	}

	public BigDecimal getGrjcjs() {
		return this.grjcjs;
	}

	public void setGrjcjs(BigDecimal grjcjs) {
		this.grjcjs = grjcjs;
	}

	public BigDecimal getGrzhye() {
		return this.grzhye;
	}

	public void setGrzhye(BigDecimal grzhye) {
		this.grzhye = grzhye;
	}

	public String getDwmc() {
		return this.dwmc;
	}

	public void setDwmc(String dwmc) {
		this.dwmc = dwmc;
	}

	public String getDwzh() {
		return this.dwzh;
	}

	public void setDwzh(String dwzh) {
		this.dwzh = dwzh;
	}

	public String getDwdh() {
		return this.dwdh;
	}

	public void setDwdh(String dwdh) {
		this.dwdh = dwdh;
	}

	public String getGrzhzt() {
		return grzhzt;
	}

	public void setGrzhzt(String grzhzt) {
		this.grzhzt = grzhzt;
	}

	public String getDwxz() {
		return dwxz;
	}

	public void setDwxz(String dwxz) {
		this.dwxz = dwxz;
	}

	public String getDwdz() {
		return this.dwdz;
	}

	public void setDwdz(String dwdz) {
		this.dwdz = dwdz;
	}

	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}

	// public String getBlzl() {
	// return blzl;
	// }
	//
	// public void setBlzl(String blzl) {
	// this.blzl = blzl;
	// }

}
