package com.handge.housingfund.database.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

/**
 * HGuaranteeExtension generated by hbm2java
 */
@Entity
@Table(name = "c_loan_guarantee_extension")
@org.hibernate.annotations.Table(appliesTo = "c_loan_guarantee_extension", comment = "保证表")
public class CLoanGuaranteeExtension extends Common implements java.io.Serializable {
	private static final long serialVersionUID = -7215789127375824221L;

	@Column(name = "BZFLX", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '保证方类型（0：个人 1：机构）'")
	private String bzflx;
	@Column(name = "FRDBXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '法人代表姓名'")
	private String frdbxm;
	@Column(name = "FRDBSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '法人代表身份证号码'")
	private String frdbsfzhm;
	@Column(name = "FRDBLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '法人代表联系电话'")
	private String frdblxdh;
	@Column(name = "FRDBXJZDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '法人代表现居住地址'")
	private String frdbxjzdz;
	@Column(name = "TXDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '通讯地址'")
	private String txdz;
	@Column(name = "YZBM", columnDefinition = "VARCHAR(6) DEFAULT NULL COMMENT '邮政编码'")
	private String yzbm;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "YWLSH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '业务流水号'")
	private String ywlsh;

	public CLoanGuaranteeExtension() {
		super();
	}

	public CLoanGuaranteeExtension(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
								   String bzflx, String frdbxm, String frdbsfzhm, String frdblxdh,
								   String frdbxjzdz, String txdz, String yzbm, String blzl, String ywlsh) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.bzflx = bzflx;
		this.frdbxm = frdbxm;
		this.frdbsfzhm = frdbsfzhm;
		this.frdblxdh = frdblxdh;
		this.frdbxjzdz = frdbxjzdz;
		this.txdz = txdz;
		this.yzbm = yzbm;
		this.blzl = blzl;
		this.ywlsh = ywlsh;
	}

	public String getBzflx() {
		return bzflx;
	}

	public void setBzflx(String bzflx) {
		this.bzflx = bzflx;
	}

	public String getFrdbxm() {
		return this.frdbxm;
	}

	public void setFrdbxm(String frdbxm) {
		this.frdbxm = frdbxm;
	}

	public String getFrdbsfzhm() {
		return this.frdbsfzhm;
	}

	public void setFrdbsfzhm(String frdbsfzhm) {
		this.frdbsfzhm = frdbsfzhm;
	}

	public String getFrdblxdh() {
		return this.frdblxdh;
	}

	public void setFrdblxdh(String frdblxdh) {
		this.frdblxdh = frdblxdh;
	}

	public String getFrdbxjzdz() {
		return this.frdbxjzdz;
	}

	public void setFrdbxjzdz(String frdbxjzdz) {
		this.frdbxjzdz = frdbxjzdz;
	}

	public String getTxdz() {
		return this.txdz;
	}

	public void setTxdz(String txdz) {
		this.txdz = txdz;
	}

	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	public String getBlzl() {
		return this.blzl;
	}

	public void setBlzl(String blzl) {
		this.blzl = blzl;
	}

	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}
}
