package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

// default package

/**
 * HEatateProjectVice generated by hbm2java
 */
@Entity
@Table(name = "c_loan_eatate_project_vice")
@org.hibernate.annotations.Table(appliesTo = "c_loan_eatate_project_vice", comment = "楼盘项目")
public class CLoanEatateProjectVice extends Common implements java.io.Serializable {

	private static final long serialVersionUID = -6376713854250254421L;

//	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinColumn(name = "GRYWMX", columnDefinition = "VARCHAR(32) DEFAULT NULL COMMENT '个人业务明细'")
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "loanEatateProjectVice")
	private CLoanHousingBusinessProcess grywmx;

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "loanHousingCompanyVice", columnDefinition = "VARCHAR(32) DEFAULT NULL COMMENT '房开公司'")
	private CLoanHousingCompanyVice loanHousingCompanyVice;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "loanEatateProjectVice")
	private List<CLoanBuildingInformationVice> loanBuildingInformationVices;

	@Column(name = "LPMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '楼盘名称'")
	private String lpmc;

	@Column(name = "LPBH", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '楼盘编号'")
	private String lpbh;
	@Column(name = "LPDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '楼盘地址'")
	private String lpdz;
	@Column(name = "YSXKZH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '预售许可证号'")
	private String ysxkzh;
	@Column(name = "HQTDDJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '获取土地单价'")
	private BigDecimal hqtddj = BigDecimal.ZERO;
	@Column(name = "HQTDZJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '获取土地总价'")
	private BigDecimal hqtdzj = BigDecimal.ZERO;
	@Column(name = "BZJBL", columnDefinition = "NUMERIC(4,2) DEFAULT NULL COMMENT '保证金比例'")
	private BigDecimal bzjbl = BigDecimal.ZERO;
	@Column(name = "JZZMJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '建筑总面积'")
	private BigDecimal jzzmj = BigDecimal.ZERO;
	@Column(name = "JZZJE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '建筑总金额'")
	private BigDecimal jzzje = BigDecimal.ZERO;
	@Column(name = "AJXYRQ", columnDefinition = "DATETIME DEFAULT NULL COMMENT '按揭协议日期'")
	private Date ajxyrq;
	@Column(name = "LXR", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '联系人'")
	private String lxr;
	@Column(name = "LXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '联系电话'")
	private String lxdh;
	@Column(name = "BeiZhu", columnDefinition = "TEXT DEFAULT NULL COMMENT '备注'")
	private String beiZhu;

	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "SFBG", columnDefinition = "BIT(1) DEFAULT NULL COMMENT '是否变更'")
	private Boolean sfbg;

	@Column(name = "FKGS", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '房开公司'")
	private String fkgs;

	public CLoanEatateProjectVice() {
		super();
	}

	public CLoanEatateProjectVice(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
			CLoanHousingBusinessProcess HHousingBusinessProcess, CLoanHousingCompanyVice HHousingCompanyVice,
			String lpmc, String lpdz, String ysxkzh, BigDecimal hqtddj, BigDecimal hqtdzj, BigDecimal bzjbl,
			BigDecimal jzzmj, BigDecimal jzzje, Date ajxyrq, String lxr, String lxdh, String beiZhu, String blzl,
			Boolean sfbg, String fkgs, List<CLoanBuildingInformationVice> HBuildingInformationVices) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.grywmx = HHousingBusinessProcess;
		this.loanHousingCompanyVice = HHousingCompanyVice;
		this.lpmc = lpmc;
		this.lpdz = lpdz;
		this.ysxkzh = ysxkzh;
		this.hqtddj = hqtddj;
		this.hqtdzj = hqtdzj;
		this.bzjbl = bzjbl;
		this.jzzmj = jzzmj;
		this.jzzje = jzzje;
		this.ajxyrq = ajxyrq;
		this.lxr = lxr;
		this.lxdh = lxdh;
		this.beiZhu = beiZhu;
		this.blzl = blzl;
		this.sfbg = sfbg;
		this.fkgs = fkgs;
		this.loanBuildingInformationVices = HBuildingInformationVices;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.updated_at = new Date();
		this.id = id;
	}

	public CLoanHousingBusinessProcess getGrywmx() {
		return grywmx;
	}

	public void setGrywmx(CLoanHousingBusinessProcess grywmx) {
		this.updated_at = new Date();
		this.grywmx = grywmx;
	}

	public String getLpmc() {
		return this.lpmc;
	}

	public void setLpmc(String lpmc) {
		this.updated_at = new Date();
		this.lpmc = lpmc;
	}

	public String getLpdz() {
		return this.lpdz;
	}

	public void setLpdz(String lpdz) {
		this.updated_at = new Date();
		this.lpdz = lpdz;
	}

	public String getYsxkzh() {
		return this.ysxkzh;
	}

	public void setYsxkzh(String ysxkzh) {
		this.updated_at = new Date();
		this.ysxkzh = ysxkzh;
	}

	public String getLpbh() {
		return lpbh;
	}

	public void setLpbh(String lpbh) {
		this.updated_at = new Date();
		this.lpbh = lpbh;
	}

	public BigDecimal getHqtddj() {
		return this.hqtddj;
	}

	public void setHqtddj(BigDecimal hqtddj) {
		this.updated_at = new Date();
		this.hqtddj = hqtddj;
	}

	public BigDecimal getHqtdzj() {
		return this.hqtdzj;
	}

	public void setHqtdzj(BigDecimal hqtdzj) {
		this.updated_at = new Date();
		this.hqtdzj = hqtdzj;
	}

	public BigDecimal getBzjbl() {
		return this.bzjbl;
	}

	public void setBzjbl(BigDecimal bzjbl) {
		this.updated_at = new Date();
		this.bzjbl = bzjbl;
	}

	public BigDecimal getJzzmj() {
		return this.jzzmj;
	}

	public void setJzzmj(BigDecimal jzzmj) {
		this.updated_at = new Date();
		this.jzzmj = jzzmj;
	}

	public BigDecimal getJzzje() {
		return this.jzzje;
	}

	public void setJzzje(BigDecimal jzzje) {
		this.updated_at = new Date();
		this.jzzje = jzzje;
	}

	public Date getAjxyrq() {
		return this.ajxyrq;
	}

	public void setAjxyrq(Date ajxyrq) {
		this.updated_at = new Date();
		this.ajxyrq = ajxyrq;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.updated_at = new Date();
		this.lxr = lxr;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.updated_at = new Date();
		this.lxdh = lxdh;
	}

	public CLoanHousingCompanyVice getLoanHousingCompanyVice() {
		return loanHousingCompanyVice;
	}

	public void setLoanHousingCompanyVice(CLoanHousingCompanyVice loanHousingCompanyVice) {
		this.updated_at = new Date();
		this.loanHousingCompanyVice = loanHousingCompanyVice;
	}

	public List<CLoanBuildingInformationVice> getLoanBuildingInformationVices() {
		return loanBuildingInformationVices;
	}

	public void setLoanBuildingInformationVices(List<CLoanBuildingInformationVice> loanBuildingInformationVices) {
		this.updated_at = new Date();
		this.loanBuildingInformationVices = loanBuildingInformationVices;
	}

	public String getBeiZhu() {
		return beiZhu;
	}

	public void setBeiZhu(String beiZhu) {
		this.updated_at = new Date();
		this.beiZhu = beiZhu;
	}

	public String getBlzl() {
		return blzl;
	}

	public void setBlzl(String blzl) {
		this.updated_at = new Date();
		this.blzl = blzl;
	}

	public Boolean getSfbg() {
		return sfbg;
	}

	public void setSfbg(Boolean sfbg) {
		this.updated_at = new Date();
		this.sfbg = sfbg;
	}

	public String getFkgs() {
		return fkgs;
	}

	public void setFkgs(String fkgs) {
		this.updated_at = new Date();
		this.fkgs = fkgs;
	}

}
