package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

// default package

/**
 * HGuaranteePledgeVice generated by hbm2java
 */
@Entity
@Table(name = "c_loan_guarantee_pledge_vice")
@org.hibernate.annotations.Table(appliesTo = "c_loan_guarantee_pledge_vice", comment = "质押表")
public class CLoanGuaranteePledgeVice extends Common implements java.io.Serializable {

    private static final long serialVersionUID = 8736245482102803066L;
    @Column(name = "ZYWSYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物所有权人姓名'")
    private String zywsyqrxm;
    @Column(name = "ZYWSYQRSFZHM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物所有权人身份证号码'")
    private String zywsyqrsfzhm;
    @Column(name = "ZYWSYQRLXDH", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物所有权人联系电话'")
    private String zywsyqrlxdh;
    @Column(name = "ZYWMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物名称'")
    private String zywmc;
    @Column(name = "ZYWJZ", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物价值'")
    private BigDecimal zywjz = BigDecimal.ZERO;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "cLoanHousingGuaranteeContractVice", columnDefinition = "VARCHAR(32) DEFAULT NULL COMMENT '担保合同信息副表'")
    private CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice;

    public CLoanGuaranteePledgeVice() {
        super();
    }

    public CLoanGuaranteePledgeVice(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
                                    String zywsyqrxm, String zywsyqrsfzhm, String zywsyqrlxdh, String zywmc, BigDecimal zywjz,
                                    CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice) {
        this.id = id;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.deleted_at = deleted_at;
        this.deleted = deleted;
        this.zywsyqrxm = zywsyqrxm;
        this.zywsyqrsfzhm = zywsyqrsfzhm;
        this.zywsyqrlxdh = zywsyqrlxdh;
        this.zywmc = zywmc;
        this.zywjz = zywjz;
        this.cLoanHousingGuaranteeContractVice = cLoanHousingGuaranteeContractVice;
    }

    public CLoanHousingGuaranteeContractVice getcLoanHousingGuaranteeContractVice() {
        return cLoanHousingGuaranteeContractVice;
    }

    public void setcLoanHousingGuaranteeContractVice(CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice) {
        this.updated_at = new Date();
        this.cLoanHousingGuaranteeContractVice = cLoanHousingGuaranteeContractVice;
    }

    public String getZywsyqrxm() {
        return zywsyqrxm;
    }

    public void setZywsyqrxm(String zywsyqrxm) {
        this.updated_at = new Date();
        this.zywsyqrxm = zywsyqrxm;
    }

    public String getZywsyqrsfzhm() {
        return zywsyqrsfzhm;
    }

    public void setZywsyqrsfzhm(String zywsyqrsfzhm) {
        this.updated_at = new Date();
        this.zywsyqrsfzhm = zywsyqrsfzhm;
    }

    public String getZywsyqrlxdh() {
        return zywsyqrlxdh;
    }

    public void setZywsyqrlxdh(String zywsyqrlxdh) {
        this.updated_at = new Date();
        this.zywsyqrlxdh = zywsyqrlxdh;
    }

    public String getZywmc() {
        return zywmc;
    }

    public void setZywmc(String zywmc) {
        this.updated_at = new Date();
        this.zywmc = zywmc;
    }

    public BigDecimal getZywjz() {
        return zywjz;
    }

    public void setZywjz(BigDecimal zywjz) {
        this.updated_at = new Date();
        this.zywjz = zywjz;
    }

}
