package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

// default package

/**
 * HHousePurchasingBasic generated by hbm2java
 */
@Entity
@Table(name = "c_loan_house_purchasing_basic")
@org.hibernate.annotations.Table(appliesTo = "c_loan_house_purchasing_basic", comment = "基础-房屋购买信息表")
public class CLoanHousePurchasingBasic extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 7866732133420081798L;

//	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinColumn(name = "cLoanHousingPersonInformationBasic", columnDefinition = "varchar(32) DEFAULT NULL COMMENT '贷款个人信息基础表'")
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "purchasing")
	private CLoanHousingPersonInformationBasic cLoanHousingPersonInformationBasic;

	@Column(name = "LPMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '楼盘名称'")
	private String lpmc;
	@Column(name = "DanJia", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '单价'")
	private BigDecimal danJia = BigDecimal.ZERO;
	@Column(name = "HTJE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '合同金额'")
	private BigDecimal htje = BigDecimal.ZERO;
	@Column(name = "FWZJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '房屋总价'")
	private BigDecimal fwzj = BigDecimal.ZERO;
	@Column(name = "GFHTBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '购房合同编号'")
	private String gfhtbh;
	@Column(name = "FWJZMJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '房屋建筑面积'")
	private BigDecimal fwjzmj = BigDecimal.ZERO;
	@Column(name = "FWTNMJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '房屋套内面积'")
	private BigDecimal fwtnmj = BigDecimal.ZERO;
	@Column(name = "SFK", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '首付款'")
	private BigDecimal sfk = BigDecimal.ZERO;
	@Column(name = "FWXZ", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '房屋性质（0：商品房 1：障碍性住房 2：自建房 3：两限房 4：集资房 5：危改房 6：经济适用房 7：房改房 8：其他）'")
	private String fwxz;
	@Column(name = "FWXS", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '房屋形式（0：在建房  1：现房）'")
	private String fwxs;
	@Column(name = "FWJG", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '房屋结构（0：框架 1：砖混 2：其他）'")
	private String fwjg;
	@Column(name = "FWJGRQ", columnDefinition = "DATETIME DEFAULT NULL COMMENT '房屋竣工日期'")
	private Date fwjgrq;
	@Column(name = "SFRZHHM", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '售房人账户号码'")
	private String sfrzhhm;
	@Column(name = "SFRKHYHMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '售房人开户银行名称'")
	private String sfrkhyhmc;
	@Column(name = "SFRYHKHM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '售房人银行开户名'")
	private String sfryhkhm;
	@Column(name = "YFK", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '已付款'")
	private BigDecimal yfk = BigDecimal.ZERO;
	@Column(name = "GRSKYHZH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '个人收款银行账号'")
	private String grskyhzh;
	@Column(name = "KHYHMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '开户银行名称'")
	private String khyhmc;
	@Column(name = "YHKHM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '银行开户名'")
	private String yhkhm;
	@Column(name = "SFWESF", columnDefinition = "BIT(1) DEFAULT NULL COMMENT '是否为二手房（0：否 1：是）'")
	private Boolean sfwesf;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "FWZL", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '房屋坐落'")
	private String fwzl;
	@Column(name = "LXFS", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '联系方式'")
	private String lxfs;
	@Column(name = "SFRMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '售房人名称'")
	private String sfrmc;
	@Column(name = "SPFYSXKBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '商品房预售许可编号'")
	private String spfysxkbh;

	public CLoanHousePurchasingBasic() {
	}

	public CLoanHousePurchasingBasic(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
			CLoanHousingPersonInformationBasic HHousingPersonInformationBasic, String lpmc, BigDecimal htje,
			BigDecimal fwzj, String gfhtbh, BigDecimal fwjzmj, BigDecimal fwtnmj, BigDecimal sfk, String fwxz,
			String fwxs, String fwjg, Date fwjgrq, String sfrzhhm, String sfrkhyhmc, String sfryhkhm, BigDecimal yfk,
			String grskyhzh, String khyhmc, String yhkhm, Boolean sfwesf, String blzl, BigDecimal danJia, String fwzl,
			String lxfs, String sfrmc, String spfysxkbh) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.cLoanHousingPersonInformationBasic = HHousingPersonInformationBasic;
		this.lpmc = lpmc;
		this.htje = htje;
		this.fwzj = fwzj;
		this.gfhtbh = gfhtbh;
		this.fwjzmj = fwjzmj;
		this.fwtnmj = fwtnmj;
		this.sfk = sfk;
		this.fwxz = fwxz;
		this.fwxs = fwxs;
		this.fwjg = fwjg;
		this.fwjgrq = fwjgrq;
		this.sfrzhhm = sfrzhhm;
		this.sfrkhyhmc = sfrkhyhmc;
		this.sfryhkhm = sfryhkhm;
		this.yfk = yfk;
		this.grskyhzh = grskyhzh;
		this.khyhmc = khyhmc;
		this.yhkhm = yhkhm;
		this.sfwesf = sfwesf;
		this.blzl = blzl;
		this.danJia = danJia;
		this.fwzl = fwzl;
		this.lxfs = lxfs;
		this.sfrmc = sfrmc;
		this.spfysxkbh = spfysxkbh;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CLoanHousingPersonInformationBasic getcLoanHousingPersonInformationBasic() {
		return cLoanHousingPersonInformationBasic;
	}

	public void setcLoanHousingPersonInformationBasic(
			CLoanHousingPersonInformationBasic cLoanHousingPersonInformationBasic) {
		this.updated_at = new Date();
		this.cLoanHousingPersonInformationBasic = cLoanHousingPersonInformationBasic;
	}

	public String getLpmc() {
		return this.lpmc;
	}

	public void setLpmc(String lpmc) {
		this.updated_at = new Date();
		this.lpmc = lpmc;
	}

	public BigDecimal getHtje() {
		return this.htje;
	}

	public void setHtje(BigDecimal htje) {
		this.updated_at = new Date();
		this.htje = htje;
	}

	public BigDecimal getFwzj() {
		return this.fwzj;
	}

	public void setFwzj(BigDecimal fwzj) {
		this.updated_at = new Date();
		this.fwzj = fwzj;
	}

	public String getGfhtbh() {
		return this.gfhtbh;
	}

	public void setGfhtbh(String gfhtbh) {
		this.updated_at = new Date();
		this.gfhtbh = gfhtbh;
	}

	public BigDecimal getFwjzmj() {
		return this.fwjzmj;
	}

	public void setFwjzmj(BigDecimal fwjzmj) {
		this.updated_at = new Date();
		this.fwjzmj = fwjzmj;
	}

	public BigDecimal getFwtnmj() {
		return this.fwtnmj;
	}

	public void setFwtnmj(BigDecimal fwtnmj) {
		this.updated_at = new Date();
		this.fwtnmj = fwtnmj;
	}

	public BigDecimal getSfk() {
		return this.sfk;
	}

	public void setSfk(BigDecimal sfk) {
		this.updated_at = new Date();
		this.sfk = sfk;
	}

	public String getFwxz() {
		return fwxz;
	}

	public void setFwxz(String fwxz) {
		this.updated_at = new Date();
		this.fwxz = fwxz;
	}

	public String getFwxs() {
		return fwxs;
	}

	public void setFwxs(String fwxs) {
		this.updated_at = new Date();
		this.fwxs = fwxs;
	}

	public String getFwjg() {
		return fwjg;
	}

	public void setFwjg(String fwjg) {
		this.updated_at = new Date();
		this.fwjg = fwjg;
	}

	public BigDecimal getDanJia() {
		return danJia;
	}

	public void setDanJia(BigDecimal danJia) {
		this.updated_at = new Date();
		this.danJia = danJia;
	}

	public Date getFwjgrq() {
		return fwjgrq;
	}

	public void setFwjgrq(Date fwjgrq) {
		this.updated_at = new Date();
		this.fwjgrq = fwjgrq;
	}

	public String getSfrzhhm() {
		return sfrzhhm;
	}

	public void setSfrzhhm(String sfrzhhm) {
		this.updated_at = new Date();
		this.sfrzhhm = sfrzhhm;
	}

	public String getSfrkhyhmc() {
		return sfrkhyhmc;
	}

	public void setSfrkhyhmc(String sfrkhyhmc) {
		this.updated_at = new Date();
		this.sfrkhyhmc = sfrkhyhmc;
	}

	public String getSfryhkhm() {
		return sfryhkhm;
	}

	public void setSfryhkhm(String sfryhkhm) {
		this.updated_at = new Date();
		this.sfryhkhm = sfryhkhm;
	}

	public BigDecimal getYfk() {
		return yfk;
	}

	public void setYfk(BigDecimal yfk) {
		this.updated_at = new Date();
		this.yfk = yfk;
	}

	public String getGrskyhzh() {
		return grskyhzh;
	}

	public void setGrskyhzh(String grskyhzh) {
		this.updated_at = new Date();
		this.grskyhzh = grskyhzh;
	}

	public String getKhyhmc() {
		return khyhmc;
	}

	public void setKhyhmc(String khyhmc) {
		this.updated_at = new Date();
		this.khyhmc = khyhmc;
	}

	public String getYhkhm() {
		return yhkhm;
	}

	public void setYhkhm(String yhkhm) {
		this.updated_at = new Date();
		this.yhkhm = yhkhm;
	}

	public Boolean getSfwesf() {
		return sfwesf;
	}

	public void setSfwesf(Boolean sfwesf) {
		this.updated_at = new Date();
		this.sfwesf = sfwesf;
	}

	public String getBlzl() {
		return blzl;
	}

	public void setBlzl(String blzl) {
		this.updated_at = new Date();
		this.blzl = blzl;
	}

	public String getFwzl() {
		return fwzl;
	}

	public void setFwzl(String fwzl) {
		this.updated_at = new Date();
		this.fwzl = fwzl;
	}

	public String getLxfs() {
		return lxfs;
	}

	public void setLxfs(String lxfs) {
		this.updated_at = new Date();
		this.lxfs = lxfs;
	}

	public String getSfrmc() {
		return sfrmc;
	}

	public void setSfrmc(String sfrmc) {
		this.updated_at = new Date();
		this.sfrmc = sfrmc;
	}

	public String getSpfysxkbh() {
		return spfysxkbh;
	}

	public void setSpfysxkbh(String spfysxkbh) {
		this.updated_at = new Date();
		this.spfysxkbh = spfysxkbh;
	}

}
