package com.handge.housingfund.database.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

/**
 * HGuaranteeMortgageExtension generated by hbm2java
 */
@Entity
@Table(name = "c_loan_guarantee_mortgage_extension")
@org.hibernate.annotations.Table(appliesTo = "c_loan_guarantee_mortgage_extension", comment = "抵押表")
public class CLoanGuaranteeMortgageExtension extends Common implements java.io.Serializable {

	private static final long serialVersionUID = -141544102944211599L;

	@Column(name = "DYWSYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物所有权人姓名'")
	private String dywsyqrxm;
	@Column(name = "DYWSYQRSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '抵押物所有权人身份证号码'")
	private String dywsyqrsfzhm;
	@Column(name = "DYWSYQRLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '抵押物所有权人联系电话'")
	private String dywsyqrlxdh;
	@Column(name = "DYWGYQRSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '抵押物共有权人身份证号码'")
	private String dywgyqrsfzhm;
	@Column(name = "DYWGYQRLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '抵押物共有权人联系电话'")
	private String dywgyqrlxdh;
	@Column(name = "DYWGYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物共有权人姓名'")
	private String dywgyqrxm;
	@Column(name = "DYWMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物名称'")
	private String dywmc;
	@Column(name = "QSZSBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '权属证书编号'")
	private String qszsbh;
	@Column(name = "DYWPGJZ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '抵押物评估价值'")
	private BigDecimal dywpgjz = BigDecimal.ZERO;
	@Column(name = "DYFWXS", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '抵押房屋形式（0：住宅 （期房） 1：住宅（现房） 2：商铺 3：其他）'")
	private String dyfwxs;
	@Column(name = "FWMJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '房屋面积'")
	private BigDecimal fwmj = BigDecimal.ZERO;
	@Column(name = "FWJG", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '房屋结构（0：框架 1：砖混 2：土木 3：其他）'")
	private String fwjg;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "YWLSH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '业务流水号'")
	private String ywlsh;

	@Column(name = "DYWFWZL", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '抵押物房屋坐落'")
	private String dywfwzl;

	public CLoanGuaranteeMortgageExtension(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted, String dywsyqrxm, String dywsyqrsfzhm, String dywsyqrlxdh,
										   String dywgyqrxm, String dywgyqrsfzhm, String dywgyqrlxdh, String dywmc, String qszsbh, BigDecimal dywpgjz,
										   String dyfwxs, BigDecimal fwmj, String fwjg, String blzl, String ywlsh, String dywfwzl) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.dywsyqrxm = dywsyqrxm;
		this.dywsyqrsfzhm = dywsyqrsfzhm;
		this.dywsyqrlxdh = dywsyqrlxdh;
		this.dywgyqrxm = dywgyqrxm;
		this.dywgyqrsfzhm = dywgyqrsfzhm;
		this.dywgyqrlxdh = dywgyqrlxdh;
		this.dywmc = dywmc;
		this.qszsbh = qszsbh;
		this.dywpgjz = dywpgjz;
		this.dyfwxs = dyfwxs;
		this.fwmj = fwmj;
		this.fwjg = fwjg;
		this.blzl = blzl;
		this.dywfwzl = dywfwzl;
		this.ywlsh = ywlsh;
	}

	public String getDywsyqrxm() {
		return this.dywsyqrxm;
	}

	public void setDywsyqrxm(String dywsyqrxm) {
		this.dywsyqrxm = dywsyqrxm;
	}

	public String getDywsyqrsfzhm() {
		return this.dywsyqrsfzhm;
	}

	public void setDywsyqrsfzhm(String dywsyqrsfzhm) {
		this.dywsyqrsfzhm = dywsyqrsfzhm;
	}

	public String getDywsyqrlxdh() {
		return this.dywsyqrlxdh;
	}

	public void setDywsyqrlxdh(String dywsyqrlxdh) {
		this.dywsyqrlxdh = dywsyqrlxdh;
	}

	public String getDywgyqrsfzhm() {
		return this.dywgyqrsfzhm;
	}

	public void setDywgyqrsfzhm(String dywgyqrsfzhm) {
		this.dywgyqrsfzhm = dywgyqrsfzhm;
	}

	public String getDywgyqrlxdh() {
		return this.dywgyqrlxdh;
	}

	public void setDywgyqrlxdh(String dywgyqrlxdh) {

		this.dywgyqrlxdh = dywgyqrlxdh;
	}

	public String getDywfwzl() {
		return dywfwzl;
	}

	public void setDywfwzl(String dywfwzl) {

		this.dywfwzl = dywfwzl;
	}

	public CLoanGuaranteeMortgageExtension() {
		super();
	}

	public String getDywgyqrxm() {
		return dywgyqrxm;
	}

	public void setDywgyqrxm(String dywgyqrxm) {
		this.dywgyqrxm = dywgyqrxm;
	}

	public String getDywmc() {
		return this.dywmc;
	}

	public void setDywmc(String dywmc) {
		this.dywmc = dywmc;
	}

	public String getQszsbh() {
		return this.qszsbh;
	}

	public void setQszsbh(String qszsbh) {
		this.qszsbh = qszsbh;
	}

	public BigDecimal getDywpgjz() {
		return this.dywpgjz;
	}

	public void setDywpgjz(BigDecimal dywpgjz) {
		this.dywpgjz = dywpgjz;
	}

	public BigDecimal getFwmj() {
		return this.fwmj;
	}

	public void setFwmj(BigDecimal fwmj) {
		this.fwmj = fwmj;
	}

	public String getDyfwxs() {
		return dyfwxs;
	}

	public void setDyfwxs(String dyfwxs) {
		this.dyfwxs = dyfwxs;
	}

	public String getFwjg() {
		return fwjg;
	}

	public void setFwjg(String fwjg) {
		this.fwjg = fwjg;
	}

	public String getBlzl() {
		return this.blzl;
	}

	public void setBlzl(String blzl) {
		this.blzl = blzl;
	}

	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}

}
