package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

// default package

/**
 * HBuildingInformationVice generated by hbm2java
 */
@Entity
@Table(name = "c_loan_building_information_vice")
@org.hibernate.annotations.Table(appliesTo = "c_loan_building_information_vice", comment = "楼栋信息")
public class CLoanBuildingInformationVice extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 3833603469039415210L;

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "loanEatateProjectVice", columnDefinition = "varchar(32) DEFAULT NULL COMMENT '楼栋信息'")
	private CLoanEatateProjectVice loanEatateProjectVice;
	@Column(name = "YSXKZ", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '预售许可证'")
	private String ysxkz;
	@Column(name = "LDMH", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '楼栋名/号'")
	private String ldmh;
	@Column(name = "DKBL", columnDefinition = "NUMERIC(4,2) DEFAULT NULL COMMENT '贷款比例'")
	private BigDecimal dkbl = BigDecimal.ZERO;
	@Column(name = "JGRQ", columnDefinition = "DATETIME DEFAULT NULL COMMENT '竣工日期'")
	private Date jgrq;
	@Column(name = "XYRQ", columnDefinition = "DATETIME DEFAULT NULL COMMENT '协议日期'")
	private Date xyrq;
	@Column(name = "KSDYH", columnDefinition = "NUMERIC(4,0) DEFAULT NULL COMMENT '开始单元号'")
	private BigDecimal ksdyh = BigDecimal.ZERO;
	@Column(name = "DYS", columnDefinition = "NUMERIC(4,0) DEFAULT NULL COMMENT '单元数'")
	private BigDecimal dys = BigDecimal.ZERO;
	@Column(name = "BeiZhu", columnDefinition = "TEXT DEFAULT NULL COMMENT '备注'")
	private String beiZhu;

	public CLoanBuildingInformationVice() {
		super();
	}

	public CLoanBuildingInformationVice(String id, Date created_at, boolean deleted, Date deleted_at, Date updated_at,
			CLoanEatateProjectVice HEatateProjectVice, String ldmh, BigDecimal dkbl, Date jgrq, Date xyrq,
			BigDecimal ksdyh, BigDecimal dys, String beiZhu) {
		this.id = id;
		this.created_at = created_at;
		this.deleted = deleted;
		this.deleted_at = deleted_at;
		this.updated_at = updated_at;
		this.loanEatateProjectVice = HEatateProjectVice;
		this.ldmh = ldmh;
		this.dkbl = dkbl;
		this.jgrq = jgrq;
		this.xyrq = xyrq;
		this.ksdyh = ksdyh;
		this.dys = dys;
		this.beiZhu = beiZhu;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.updated_at = new Date();
		this.id = id;
	}

	public CLoanEatateProjectVice getLoanEatateProjectVice() {
		return loanEatateProjectVice;
	}

	public void setLoanEatateProjectVice(CLoanEatateProjectVice loanEatateProjectVice) {
		this.updated_at = new Date();
		this.loanEatateProjectVice = loanEatateProjectVice;
	}

	public String getLdmh() {
		return this.ldmh;
	}

	public void setLdmh(String ldmh) {
		this.updated_at = new Date();
		this.ldmh = ldmh;
	}

	public BigDecimal getDkbl() {
		return this.dkbl;
	}

	public void setDkbl(BigDecimal dkbl) {
		this.updated_at = new Date();
		this.dkbl = dkbl;
	}

	public Date getJgrq() {
		return this.jgrq;
	}

	public void setJgrq(Date jgrq) {
		this.updated_at = new Date();
		this.jgrq = jgrq;
	}

	public Date getXyrq() {
		return this.xyrq;
	}

	public void setXyrq(Date xyrq) {
		this.updated_at = new Date();
		this.xyrq = xyrq;
	}

	public BigDecimal getKsdyh() {
		return this.ksdyh;
	}

	public void setKsdyh(BigDecimal ksdyh) {
		this.updated_at = new Date();
		this.ksdyh = ksdyh;
	}

	public BigDecimal getDys() {
		return this.dys;
	}

	public void setDys(BigDecimal dys) {
		this.updated_at = new Date();
		this.dys = dys;
	}

	public String getBeiZhu() {
		return this.beiZhu;
	}

	public void setBeiZhu(String beiZhu) {
		this.updated_at = new Date();
		this.beiZhu = beiZhu;
	}

	public String getYsxkz() {
		return ysxkz;
	}

	public void setYsxkz(String ysxkz) {
		this.ysxkz = ysxkz;
	}
}
