package com.handge.housingfund.database.entities;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

// default package
// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

/**
 * HHousingCoborrowerVice generated by hbm2java
 */
@Entity
@Table(name = "c_loan_housing_coborrower_vice")
@org.hibernate.annotations.Table(appliesTo = "c_loan_housing_coborrower_vice", comment = "贷款发放-共同借款人信息表")
public class CLoanHousingCoborrowerVice extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 6648115658199790169L;
	@Column(name = "CDGX", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '参贷关系'")
	private String cdgx;
	@Column(name = "GDDHHM", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '固定电话号码'")
	private String gddhhm;
	@Column(name = "GTJKRGJJZH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '共合借款人公积金账号'")
	private String gtjkrgjjzh;
	@Column(name = "GTJKRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '共同借款人姓名'")
	private String gtjkrxm;
	@Column(name = "GTJKRZJHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '共同借款人证件号码'")
	private String gtjkrzjhm;
	@Column(name = "GTJKRZJLX", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '共同借款人证件类型'")
	private String gtjkrzjlx;
	@Column(name = "JKHTBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '借款合同编号'")
	private String jkhtbh;
	@Column(name = "SJHM", columnDefinition = "VARCHAR(11) DEFAULT NULL COMMENT '手机号码'")
	private String sjhm;
	@Column(name = "YSR", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '月收入'")
	private BigDecimal ysr = BigDecimal.ZERO;
	@Column(name = "JCD", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '缴存地'")
	private String jcd;
	@Column(name = "HKSZD", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '户口所在地'")
	private String hkszd;
	@Column(name = "JZNY", columnDefinition = "VARCHAR(6) DEFAULT NULL COMMENT '缴至年月'")
	private String jzny;
	@Column(name = "GRZHZT", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '个人账户状态'")
	private String grzhzt;
	@Column(name = "LXZCJCYS", columnDefinition = "decimal(18,2) DEFAULT NULL COMMENT '连续正常缴存月数'")
	private BigDecimal lxzcjcys = BigDecimal.ZERO;
	@Column(name = "YJCE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '月缴存额'")
	private BigDecimal yjce = BigDecimal.ZERO;
	@Column(name = "GRJCJS", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '个人缴存基数'")
	private BigDecimal grjcjs = BigDecimal.ZERO;
	@Column(name = "GRZHYE", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '个人账户余额'")
	private BigDecimal grzhye = BigDecimal.ZERO;
	@Column(name = "DWMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '单位名称'")
	private String dwmc;
	@Column(name = "DWZH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '单位账号'")
	private String dwzh;
	@Column(name = "DWDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '单位电话'")
	private String dwdh;
	@Column(name = "DWXZ", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '单位性质'")
	private String dwxz;
	@Column(name = "DWDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '单位地址'")
	private String dwdz;

	public String getBlzl() {
		return blzl;
	}

	public void setBlzl(String blzl) {
		this.updated_at = new Date();
		this.blzl = blzl;
	}

	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
//	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinColumn(name = "GRYWMX", columnDefinition = "VARCHAR(32) DEFAULT NULL COMMENT '个人业务明细'")
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "loanHousingCoborrowerVice")
	private CLoanHousingBusinessProcess grywmx;

	public CLoanHousingCoborrowerVice() {
		super();

	}

	public CLoanHousingCoborrowerVice(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
			String cdgx, String gddhhm, String gtjkrgjjzh, String gtjkrxm, String gtjkrzjhm, String gtjkrzjlx,
			String jkhtbh, String sjhm, BigDecimal ysr, String jcd, String hkszd, String jzny, String grzhzt,
			BigDecimal lxzcjcys, BigDecimal yjce, BigDecimal grjcjs, BigDecimal grzhye, String dwmc, String dwzh,
			String dwdh, String dwxz, String dwdz, CLoanHousingBusinessProcess HHousingBusinessProcessId) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.cdgx = cdgx;
		this.gddhhm = gddhhm;
		this.gtjkrgjjzh = gtjkrgjjzh;
		this.gtjkrxm = gtjkrxm;
		this.gtjkrzjhm = gtjkrzjhm;
		this.gtjkrzjlx = gtjkrzjlx;
		this.jkhtbh = jkhtbh;
		this.sjhm = sjhm;
		this.ysr = ysr;
		this.jcd = jcd;
		this.hkszd = hkszd;
		this.jzny = jzny;
		this.grzhzt = grzhzt;
		this.lxzcjcys = lxzcjcys;
		this.yjce = yjce;
		this.grjcjs = grjcjs;
		this.grzhye = grzhye;
		this.dwmc = dwmc;
		this.dwzh = dwzh;
		this.dwdh = dwdh;
		this.dwxz = dwxz;
		this.dwdz = dwdz;
		this.grywmx = HHousingBusinessProcessId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.updated_at = new Date();
		this.id = id;
	}

	public String getCdgx() {
		return this.cdgx;
	}

	public void setCdgx(String cdgx) {
		this.updated_at = new Date();
		this.cdgx = cdgx;
	}

	public String getGddhhm() {
		return this.gddhhm;
	}

	public void setGddhhm(String gddhhm) {
		this.updated_at = new Date();
		this.gddhhm = gddhhm;
	}

	public String getGtjkrgjjzh() {
		return this.gtjkrgjjzh;
	}

	public void setGtjkrgjjzh(String gtjkrgjjzh) {
		this.updated_at = new Date();
		this.gtjkrgjjzh = gtjkrgjjzh;
	}

	public String getGtjkrxm() {
		return this.gtjkrxm;
	}

	public void setGtjkrxm(String gtjkrxm) {
		this.updated_at = new Date();
		this.gtjkrxm = gtjkrxm;
	}

	public String getGtjkrzjhm() {
		return this.gtjkrzjhm;
	}

	public void setGtjkrzjhm(String gtjkrzjhm) {
		this.updated_at = new Date();
		this.gtjkrzjhm = gtjkrzjhm;
	}

	public String getGtjkrzjlx() {
		return this.gtjkrzjlx;
	}

	public void setGtjkrzjlx(String gtjkrzjlx) {
		this.updated_at = new Date();
		this.gtjkrzjlx = gtjkrzjlx;
	}

	public String getJkhtbh() {
		return this.jkhtbh;
	}

	public void setJkhtbh(String jkhtbh) {
		this.updated_at = new Date();
		this.jkhtbh = jkhtbh;
	}

	public String getSjhm() {
		return this.sjhm;
	}

	public void setSjhm(String sjhm) {
		this.updated_at = new Date();
		this.sjhm = sjhm;
	}

	public BigDecimal getYsr() {
		return this.ysr;
	}

	public void setYsr(BigDecimal ysr) {
		this.updated_at = new Date();
		this.ysr = ysr;
	}

	public String getJcd() {
		return this.jcd;
	}

	public void setJcd(String jcd) {
		this.updated_at = new Date();
		this.jcd = jcd;
	}

	public String getHkszd() {
		return this.hkszd;
	}

	public void setHkszd(String hkszd) {
		this.updated_at = new Date();
		this.hkszd = hkszd;
	}

	public String getJzny() {
		return this.jzny;
	}

	public void setJzny(String jzny) {
		this.updated_at = new Date();
		this.jzny = jzny;
	}

	public BigDecimal getLxzcjcys() {
		return this.lxzcjcys;
	}

	public void setLxzcjcys(BigDecimal lxzcjcys) {
		this.updated_at = new Date();
		this.lxzcjcys = lxzcjcys;
	}

	public BigDecimal getYjce() {
		return this.yjce;
	}

	public void setYjce(BigDecimal yjce) {
		this.updated_at = new Date();
		this.yjce = yjce;
	}

	public BigDecimal getGrjcjs() {
		return this.grjcjs;
	}

	public void setGrjcjs(BigDecimal grjcjs) {
		this.updated_at = new Date();
		this.grjcjs = grjcjs;
	}

	public BigDecimal getGrzhye() {
		return this.grzhye;
	}

	public void setGrzhye(BigDecimal grzhye) {
		this.updated_at = new Date();
		this.grzhye = grzhye;
	}

	public String getDwmc() {
		return this.dwmc;
	}

	public void setDwmc(String dwmc) {
		this.updated_at = new Date();
		this.dwmc = dwmc;
	}

	public String getDwzh() {
		return this.dwzh;
	}

	public void setDwzh(String dwzh) {
		this.updated_at = new Date();
		this.dwzh = dwzh;
	}

	public String getDwdh() {
		return this.dwdh;
	}

	public void setDwdh(String dwdh) {
		this.updated_at = new Date();
		this.dwdh = dwdh;
	}

	public String getGrzhzt() {
		return grzhzt;
	}

	public void setGrzhzt(String grzhzt) {
		this.updated_at = new Date();
		this.grzhzt = grzhzt;
	}

	public String getDwxz() {
		return dwxz;
	}

	public void setDwxz(String dwxz) {
		this.updated_at = new Date();
		this.dwxz = dwxz;
	}

	public String getDwdz() {
		return this.dwdz;
	}

	public void setDwdz(String dwdz) {
		this.updated_at = new Date();
		this.dwdz = dwdz;
	}

	public CLoanHousingBusinessProcess getGrywmx() {
		return grywmx;
	}

	public void setGrywmx(CLoanHousingBusinessProcess grywmx) {
		this.updated_at = new Date();
		this.grywmx = grywmx;
	}
}
