package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * HHousingCompanyBasic generated by hbm2java
 */
@Entity
@Table(name = "c_loan_housing_company_basic")
@org.hibernate.annotations.Table(appliesTo = "c_loan_housing_company_basic", comment = "房开公司基础表")
public class CLoanHousingCompanyBasic extends Common implements java.io.Serializable {

	private static final long serialVersionUID = -2760583842909769259L;
	@Column(name = "FKGS", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '房开公司'")
	private String fkgs;
	@Column(name = "FKGSZH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '房开公司账号'")
	private String fkgszh;
	@Column(name = "SJFLB", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '售建房类别（0：开发商 1：个人 2：其他）'")
	private String sjflb;
	@Column(name = "ZZDJ", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '资质等级（0：一级 1：二级 2：三级 3：四级）'")
	private String zzdj;
	@Column(name = "DWDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '单位地址'")
	private String dwdz;
	@Column(name = "ZCDZ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '注册地址'")
	private String zcdz;
	@Column(name = "ZCZJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '注册资金'")
	private BigDecimal zczj = BigDecimal.ZERO;
	@Column(name = "FRDB", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '法人代表'")
	private String frdb;
	@Column(name = "FRDBZJLX", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '法人代表证件类型（0：身份证 1：军官证 2：护照 3：外国人永久居留证 4：其他）'")
	private String frdbzjlx;
	@Column(name = "FRDBZJHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '法人代表证件号码'")
	private String frdbzjhm;
	// @Column(name = "SFRKHYHMC", columnDefinition = " varchar(255) DEFAULT
	// NULL COMMENT '售房人开户银行名称'")
	// private String sfrkhyhmc;
	// @Column(name = "SFRKHYHKHM", columnDefinition = " varchar(255) DEFAULT
	// NULL COMMENT '售房人开户银行开户名'")
	// private String sfrkhyhkhm;
	// @Column(name = "SFRZHHM", columnDefinition = " varchar(255) DEFAULT NULL
	// COMMENT '售房人账户号码'")
	// private String sfrzhhm;
	@Column(name = "LXR", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '联系人'")
	private String lxr;
	@Column(name = "LXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '联系电话'")
	private String lxdh;
	@Column(name = "ZZJGDM", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '组织机构代码'")
	private String zzjgdm;
	@Column(name = "BeiZhu", columnDefinition = "TEXT DEFAULT NULL COMMENT '备注'")
	private String beiZhu;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "BZJZH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '保证金账户'")
	private String bzjzh;
	@Column(name = "BZJZHKHH", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '保证金账户开户行'")
	private String bzjzhkhh;
	@Column(name = "BZJKHM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '保证金开户名'")
	private String bzjkhm;
	@Column(name = "CZY", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '操作员'")
	private String czy;
	@Column(name = "YWWD", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '业务网点'")
	private String ywwd;
	@Column(name = "SFBG", columnDefinition = "BIT(1) DEFAULT NULL COMMENT '是否变更'")
	private Boolean sfbg;
	@Column(name = "SFQY", columnDefinition = "BIT(1) DEFAULT NULL COMMENT '是否启用'")
	private Boolean sfqy;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cLoanHousingCompanyBasic")
	private List<CLoanEatateProjectBasic> cLoanEatateProjectBasics;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "fkgszb")
	private List<CLoanHousingCompanyBasicExtension> cLoanHousingCompanyBasicExtensions;

	public CLoanHousingCompanyBasic() {
	}

	public CLoanHousingCompanyBasic(String fkgs, String fkgszh, String sjflb, String zzdj, String dwdz, String zcdz,
			BigDecimal zczj, String frdb, String frdbzjlx, String sfrzhhm, String lxr, String lxdh, String zzjgdm,
			String beiZhu, String blzl, String bzjzh, String bzjzhkhh, String bzjkhm, String czy, String ywwd,
			Boolean sfbg, Boolean sfqy, List<CLoanEatateProjectBasic> cLoanEatateProjectBasics,
			List<CLoanHousingCompanyBasicExtension> cLoanHousingCompanyBasicExtensions) {
		this.fkgs = fkgs;
		this.fkgszh = fkgszh;
		this.sjflb = sjflb;
		this.zzdj = zzdj;
		this.dwdz = dwdz;
		this.zcdz = zcdz;
		this.zczj = zczj;
		this.frdb = frdb;
		this.frdbzjlx = frdbzjlx;
		this.frdbzjhm = sfrzhhm;
		this.lxr = lxr;
		this.lxdh = lxdh;
		this.zzjgdm = zzjgdm;
		this.beiZhu = beiZhu;
		this.blzl = blzl;
		this.bzjzh = bzjzh;
		this.bzjzhkhh = bzjzhkhh;
		this.bzjkhm = bzjkhm;
		this.czy = czy;
		this.ywwd = ywwd;
		this.sfbg = sfbg;
		this.sfqy = sfqy;
		this.cLoanEatateProjectBasics = cLoanEatateProjectBasics;
		this.cLoanHousingCompanyBasicExtensions = cLoanHousingCompanyBasicExtensions;
	}

	public String getCzy() {
		return czy;
	}

	public void setCzy(String czy) {
		this.czy = czy;
	}

	public String getYwwd() {
		return ywwd;
	}

	public void setYwwd(String ywwd) {
		this.ywwd = ywwd;
	}

	public List<CLoanEatateProjectBasic> getcLoanEatateProjectBasics() {
		return cLoanEatateProjectBasics;
	}

	public void setcLoanEatateProjectBasics(List<CLoanEatateProjectBasic> cLoanEatateProjectBasics) {
		this.cLoanEatateProjectBasics = cLoanEatateProjectBasics;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFkgszh() {
		return fkgszh;
	}

	public void setFkgszh(String fkgszh) {
		this.updated_at = new Date();
		this.fkgszh = fkgszh;
	}

	public Boolean getSfqy() {
		return sfqy;
	}

	public void setSfqy(Boolean sfqy) {
		this.updated_at = new Date();
		this.sfqy = sfqy;
	}

	public String getFkgs() {
		return this.fkgs;
	}

	public void setFkgs(String fkgs) {
		this.updated_at = new Date();
		this.fkgs = fkgs;
	}

	public String getSjflb() {
		return sjflb;
	}

	public void setSjflb(String sjflb) {
		this.updated_at = new Date();
		this.sjflb = sjflb;
	}

	public String getZzdj() {
		return zzdj;
	}

	public void setZzdj(String zzdj) {
		this.updated_at = new Date();
		this.zzdj = zzdj;
	}

	public String getFrdbzjlx() {
		return frdbzjlx;
	}

	public void setFrdbzjlx(String frdbzjlx) {
		this.updated_at = new Date();
		this.frdbzjlx = frdbzjlx;
	}

	public String getDwdz() {
		return this.dwdz;
	}

	public void setDwdz(String dwdz) {
		this.updated_at = new Date();
		this.dwdz = dwdz;
	}

	public String getZcdz() {
		return this.zcdz;
	}

	public void setZcdz(String zcdz) {
		this.updated_at = new Date();
		this.zcdz = zcdz;
	}

	public BigDecimal getZczj() {
		return this.zczj;
	}

	public void setZczj(BigDecimal zczj) {
		this.updated_at = new Date();
		this.zczj = zczj;
	}

	public String getFrdb() {
		return this.frdb;
	}

	public void setFrdb(String frdb) {
		this.updated_at = new Date();
		this.frdb = frdb;
	}

	public List<CLoanHousingCompanyBasicExtension> getcLoanHousingCompanyBasicExtensions() {
		return cLoanHousingCompanyBasicExtensions;
	}

	public void setcLoanHousingCompanyBasicExtensions(
			List<CLoanHousingCompanyBasicExtension> cLoanHousingCompanyBasicExtensions) {
		this.updated_at = new Date();
		this.cLoanHousingCompanyBasicExtensions = cLoanHousingCompanyBasicExtensions;
	}

	// public String getFrdbzjhm() {
	// return this.frdbzjhm;
	// }
	//
	// public void setFrdbzjhm(String frdbzjhm) {
	// this.frdbzjhm = frdbzjhm;
	// }
	//
	//
	// public String getSfrkhyhmc() {
	// return this.sfrkhyhmc;
	// }
	//
	// public void setSfrkhyhmc(String sfrkhyhmc) {
	// this.sfrkhyhmc = sfrkhyhmc;
	// }
	//
	//
	// public String getSfrkhyhkhm() {
	// return this.sfrkhyhkhm;
	// }
	//
	// public void setSfrkhyhkhm(String sfrkhyhkhm) {
	// this.sfrkhyhkhm = sfrkhyhkhm;
	// }

	public String getFrdbzjhm() {
		return frdbzjhm;
	}

	public void setFrdbzjhm(String frdbzjhm) {
		this.updated_at = new Date();
		this.frdbzjhm = frdbzjhm;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.updated_at = new Date();
		this.lxr = lxr;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.updated_at = new Date();
		this.lxdh = lxdh;
	}

	public String getZzjgdm() {
		return this.zzjgdm;
	}

	public void setZzjgdm(String zzjgdm) {
		this.updated_at = new Date();
		this.zzjgdm = zzjgdm;
	}

	public String getBeiZhu() {
		return this.beiZhu;
	}

	public void setBeiZhu(String beiZhu) {
		this.updated_at = new Date();
		this.beiZhu = beiZhu;
	}

	public String getBlzl() {
		return this.blzl;
	}

	public void setBlzl(String blzl) {
		this.updated_at = new Date();
		this.blzl = blzl;
	}

	public String getBzjzh() {
		return this.bzjzh;
	}

	public void setBzjzh(String bzjzh) {
		this.updated_at = new Date();
		this.bzjzh = bzjzh;
	}

	public String getBzjzhkhh() {
		return this.bzjzhkhh;
	}

	public void setBzjzhkhh(String bzjzhkhh) {
		this.updated_at = new Date();
		this.bzjzhkhh = bzjzhkhh;
	}

	public String getBzjkhm() {
		return this.bzjkhm;
	}

	public void setBzjkhm(String bzjkhm) {
		this.updated_at = new Date();
		this.bzjkhm = bzjkhm;
	}

	public Boolean getSfbg() {
		return this.sfbg;
	}

	public void setSfbg(Boolean sfbg) {
		this.updated_at = new Date();
		this.sfbg = sfbg;
	}

}