package com.handge.housingfund.database.entities;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

// default package
// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

/**
 * HGuaranteeMortgageVice generated by hbm2java
 */
@Entity
@Table(name = "c_loan_guarantee_mortgage_vice")
@org.hibernate.annotations.Table(appliesTo = "c_loan_guarantee_mortgage_vice", comment = "抵押表")
public class CLoanGuaranteeMortgageVice extends Common implements java.io.Serializable {

    private static final long serialVersionUID = -7780792040360517285L;
    @Column(name = "DYWSYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物所有权人姓名'")
    private String dywsyqrxm;
    @Column(name = "DYWSYQRSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '抵押物所有权人身份证号码'")
    private String dywsyqrsfzhm;
    @Column(name = "DYWSYQRLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '抵押物所有权人联系电话'")
    private String dywsyqrlxdh;
    @Column(name = "DYWGYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物共有权人姓名'")
    private String dywgyqrxm;
    @Column(name = "DYWGYQRSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '抵押物共有权人身份证号码'")
    private String dywgyqrsfzhm;
    @Column(name = "DYWGYQRLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '抵押物共有权人联系电话'")
    private String dywgyqrlxdh;
    @Column(name = "DYWMC", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '抵押物名称'")
    private String dywmc;
    @Column(name = "QSZSBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '权属证书编号'")
    private String qszsbh;
    @Column(name = "DYWPGJZ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '抵押物评估价值'")
    private BigDecimal dywpgjz = BigDecimal.ZERO;
    @Column(name = "DYFWXS", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '抵押房屋形式（0：住宅 （期房） 1：住宅（现房） 2：商铺 3：其他）'")
    private String dyfwxs;
    @Column(name = "FWMJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '房屋面积'")
    private BigDecimal fwmj = BigDecimal.ZERO;
    @Column(name = "FWJG", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '房屋结构（0：框架 1：砖混 2：土木 3：其他）'")
    private String fwjg;
    @Column(name = "DYWFWZL", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '抵押物房屋坐落'")
    private String dywfwzl;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "cLoanHousingGuaranteeContractVice", columnDefinition = "VARCHAR(32) DEFAULT NULL COMMENT '担保合同信息副表'")
    private CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice;

    public CLoanGuaranteeMortgageVice() {
    }

    public CLoanGuaranteeMortgageVice(String id, Date created_at, Date updated_at, Date deleted_at, Boolean deleted,
                                      String dywsyqrxm, String dywsyqrsfzhm, String dywsyqrlxdh, String dywgyqrsfzhm, String dywgyqrlxdh,
                                      String dywmc, String qszsbh, BigDecimal dywpgjz, String dyfwxs, BigDecimal fwmj, String fwjg,
                                      String dywfwzl, String dywgyqrxm, CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice) {
        this.id = id;
        this.created_at = created_at;
        this.updated_at = deleted_at;
        this.deleted_at = updated_at;
        this.deleted = deleted;
        this.dywsyqrxm = dywsyqrxm;
        this.dywsyqrsfzhm = dywsyqrsfzhm;
        this.dywsyqrlxdh = dywsyqrlxdh;
        this.dywgyqrsfzhm = dywgyqrsfzhm;
        this.dywgyqrlxdh = dywgyqrlxdh;
        this.dywmc = dywmc;
        this.qszsbh = qszsbh;
        this.dywpgjz = dywpgjz;
        this.dyfwxs = dyfwxs;
        this.fwmj = fwmj;
        this.fwjg = fwjg;
        this.dywfwzl = dywfwzl;
        this.dywgyqrxm = dywgyqrxm;
        this.cLoanHousingGuaranteeContractVice = cLoanHousingGuaranteeContractVice;
    }

    public CLoanHousingGuaranteeContractVice getcLoanHousingGuaranteeContractVice() {
        return cLoanHousingGuaranteeContractVice;
    }

    public void setcLoanHousingGuaranteeContractVice(CLoanHousingGuaranteeContractVice cLoanHousingGuaranteeContractVice) {
        this.updated_at = new Date();
        this.cLoanHousingGuaranteeContractVice = cLoanHousingGuaranteeContractVice;
    }

    public String getDywgyqrxm() {
        return dywgyqrxm;
    }

    public void setDywgyqrxm(String dywgyqrxm) {
        this.updated_at = new Date();
        this.dywgyqrxm = dywgyqrxm;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.updated_at = new Date();
        this.id = id;
    }

    public String getDywsyqrxm() {
        return this.dywsyqrxm;
    }

    public void setDywsyqrxm(String dywsyqrxm) {
        this.updated_at = new Date();
        this.dywsyqrxm = dywsyqrxm;
    }

    public String getDywsyqrsfzhm() {
        return this.dywsyqrsfzhm;
    }

    public void setDywsyqrsfzhm(String dywsyqrsfzhm) {
        this.updated_at = new Date();
        this.dywsyqrsfzhm = dywsyqrsfzhm;
    }

    public String getDywsyqrlxdh() {
        return this.dywsyqrlxdh;
    }

    public void setDywsyqrlxdh(String dywsyqrlxdh) {
        this.updated_at = new Date();
        this.dywsyqrlxdh = dywsyqrlxdh;
    }

    public String getDywgyqrsfzhm() {
        return this.dywgyqrsfzhm;
    }

    public void setDywgyqrsfzhm(String dywgyqrsfzhm) {
        this.updated_at = new Date();
        this.dywgyqrsfzhm = dywgyqrsfzhm;
    }

    public String getDywgyqrlxdh() {
        return this.dywgyqrlxdh;
    }

    public void setDywgyqrlxdh(String dywgyqrlxdh) {
        this.updated_at = new Date();
        this.dywgyqrlxdh = dywgyqrlxdh;
    }

    public String getDywmc() {
        return this.dywmc;
    }

    public void setDywmc(String dywmc) {
        this.updated_at = new Date();
        this.dywmc = dywmc;
    }

    public String getQszsbh() {
        return this.qszsbh;
    }

    public void setQszsbh(String qszsbh) {
        this.updated_at = new Date();
        this.qszsbh = qszsbh;
    }

    public BigDecimal getDywpgjz() {
        return this.dywpgjz;
    }

    public void setDywpgjz(BigDecimal dywpgjz) {
        this.updated_at = new Date();
        this.dywpgjz = dywpgjz;
    }

    public String getDyfwxs() {
        return dyfwxs;
    }

    public void setDyfwxs(String dyfwxs) {
        this.updated_at = new Date();
        this.dyfwxs = dyfwxs;
    }

    public String getFwjg() {
        return fwjg;
    }

    public void setFwjg(String fwjg) {
        this.updated_at = new Date();
        this.fwjg = fwjg;
    }

    public BigDecimal getFwmj() {
        return this.fwmj;
    }

    public void setFwmj(BigDecimal fwmj) {
        this.updated_at = new Date();
        this.fwmj = fwmj;
    }

    public String getDywfwzl() {
        return this.dywfwzl;
    }

    public void setDywfwzl(String dywfwzl) {
        this.updated_at = new Date();
        this.dywfwzl = dywfwzl;
    }

}
