package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * HHousingPersonalLoanExtension generated by hbm2java
 */
@Entity
@Table(name = "c_loan_housing_personal_loan_extension")
@org.hibernate.annotations.Table(appliesTo = "c_loan_housing_personal_loan_extension", comment = "个人贷款合同拓展")
public class CLoanHousingPersonalLoanExtension extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 827443890293623330L;

	@Column(name = "DKYT", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '贷款用途'")
	private String dkyt;
	@Column(name = "SJHM", columnDefinition = "VARCHAR(11) DEFAULT NULL COMMENT '手机号码'")
	private String sjhm;
	@Column(name = "JHJZZJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '计划建造总价'")
	private BigDecimal jhjzzj = BigDecimal.ZERO;
	@Column(name = "GRSYZJ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '个人使用资金'")
	private BigDecimal grsyzj = BigDecimal.ZERO;
	@Column(name = "GRSKYHZH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '个人收款银行账号'")
	private String grskyhzh;
	@Column(name = "KHYHMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '开户银行名称'")
	private String khyhmc;
	@Column(name = "KHHM", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '开户户名'")
	private String khhm;
	@Column(name = "JHFXFY", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '计划翻修费用'")
	private BigDecimal jhfxfy = BigDecimal.ZERO;
	@Column(name = "DKHTWJ", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '贷款合同文件'")
	private String dkhtwj;
	@Column(name = "YJKHTBH", columnDefinition = "VARCHAR(30) DEFAULT NULL COMMENT '原借款合同编号'")
	private String yjkhtbh;



	@Column(name = "HKZHHM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '还款账号户名'")
	private String hkzhhm;
	public CLoanHousingPersonalLoanExtension() {
	}

	public CLoanHousingPersonalLoanExtension(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted, String yjkhtbh, String dkyt, String sjhm, BigDecimal jhjzzj,
											 BigDecimal grsyzj, String grskyhzh, String khyhmc, String khhm, BigDecimal jhfxfy, String dkhtwj,String hkzhhm) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.dkyt = dkyt;
		this.sjhm = sjhm;
		this.jhjzzj = jhjzzj;
		this.grsyzj = grsyzj;
		this.grskyhzh = grskyhzh;
		this.khyhmc = khyhmc;
		this.khhm = khhm;
		this.jhfxfy = jhfxfy;
		this.dkhtwj = dkhtwj;
		this.yjkhtbh = yjkhtbh;
		this.hkzhhm = hkzhhm;
	}
	public String getHkzhhm() { return hkzhhm; }

	public void setHkzhhm(String hkzhhm) { this.hkzhhm = hkzhhm; }

	public String getDkyt() {
		return dkyt;
	}

	public void setDkyt(String dkyt) {
		this.dkyt = dkyt;
	}

	public String getSjhm() {
		return sjhm;
	}

	public void setSjhm(String sjhm) {
		this.sjhm = sjhm;
	}

	public BigDecimal getJhjzzj() {
		return jhjzzj;
	}

	public void setJhjzzj(BigDecimal jhjzzj) {
		this.jhjzzj = jhjzzj;
	}

	public BigDecimal getGrsyzj() {
		return grsyzj;
	}

	public void setGrsyzj(BigDecimal grsyzj) {
		this.grsyzj = grsyzj;
	}

	public String getGrskyhzh() {
		return grskyhzh;
	}

	public void setGrskyhzh(String grskyhzh) {
		this.grskyhzh = grskyhzh;
	}

	public String getKhyhmc() {
		return khyhmc;
	}

	public void setKhyhmc(String khyhmc) {
		this.khyhmc = khyhmc;
	}

	public String getKhhm() {
		return khhm;
	}

	public void setKhhm(String khhm) {
		this.khhm = khhm;
	}

	public BigDecimal getJhfxfy() {
		return jhfxfy;
	}

	public void setJhfxfy(BigDecimal jhfxfy) {
		this.jhfxfy = jhfxfy;
	}

	public String getDkhtwj() {
		return dkhtwj;
	}

	public void setDkhtwj(String dkhtwj) {
		this.dkhtwj = dkhtwj;
	}

	public String getYjkhtbh() {
		return yjkhtbh;
	}

	public void setYjkhtbh(String yjkhtbh) {
		this.yjkhtbh = yjkhtbh;
	}

}
