package com.handge.housingfund.database.entities;

// Generated 2017-8-8 15:42:03 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * HGuaranteePledgeExtension generated by hbm2java
 */
@Entity
@Table(name = "c_loan_guarantee_pledge_extension")
@org.hibernate.annotations.Table(appliesTo = "c_loan_guarantee_pledge_extension", comment = "质押表")
public class CLoanGuaranteePledgeExtension extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 7588075503252382238L;

	@Column(name = "ZYWSYQRXM", columnDefinition = "VARCHAR(120) DEFAULT NULL COMMENT '质押物所有权人姓名'")
	private String zywsyqrxm;
	@Column(name = "ZYWSYQRSFZHM", columnDefinition = "VARCHAR(18) DEFAULT NULL COMMENT '质押物所有权人身份证号码'")
	private String zywsyqrsfzhm;
	@Column(name = "ZYWSYQRLXDH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '质押物所有权人联系电话'")
	private String zywsyqrlxdh;
	@Column(name = "BLZL", columnDefinition = "TEXT DEFAULT NULL COMMENT '办理资料'")
	private String blzl;
	@Column(name = "YWLSH", columnDefinition = "VARCHAR(20) DEFAULT NULL COMMENT '业务流水号'")
	private String ywlsh;
	@Column(name = "ZYWMC", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '质押物名称'")
	private String zywmc;
	@Column(name = "ZYWJZ", columnDefinition = "NUMERIC(18,2) DEFAULT NULL COMMENT '质押物价值'")
	private BigDecimal zywjz = BigDecimal.ZERO;

	public CLoanGuaranteePledgeExtension() {
		super();
	}

	public CLoanGuaranteePledgeExtension(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted,
										 String zywsyqrxm, String zywsyqrsfzhm, String zywsyqrlxdh,
										 String blzl, String ywlsh, String zywmc, BigDecimal zywjz) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.zywsyqrxm = zywsyqrxm;
		this.zywsyqrsfzhm = zywsyqrsfzhm;
		this.zywsyqrlxdh = zywsyqrlxdh;
		this.blzl = blzl;
		this.ywlsh = ywlsh;
		this.zywmc = zywmc;
		this.zywjz = zywjz;
	}

	public String getZywsyqrxm() {
		return this.zywsyqrxm;
	}

	public void setZywsyqrxm(String zywsyqrxm) {

		this.zywsyqrxm = zywsyqrxm;
	}

	public String getZywsyqrsfzhm() {
		return this.zywsyqrsfzhm;
	}

	public void setZywsyqrsfzhm(String zywsyqrsfzhm) {
		this.zywsyqrsfzhm = zywsyqrsfzhm;
	}

	public String getZywsyqrlxdh() {
		return this.zywsyqrlxdh;
	}

	public void setZywsyqrlxdh(String zywsyqrlxdh) {
		this.zywsyqrlxdh = zywsyqrlxdh;
	}

	public String getBlzl() {
		return this.blzl;
	}

	public void setBlzl(String blzl) {
		this.blzl = blzl;
	}

	public String getYwlsh() {
		return this.ywlsh;
	}

	public void setYwlsh(String ywlsh) {
		this.ywlsh = ywlsh;
	}

	public String getZywmc() {
		return zywmc;
	}

	public void setZywmc(String zywmc) {
		this.zywmc = zywmc;
	}

	public BigDecimal getZywjz() {
		return zywjz;
	}

	public void setZywjz(BigDecimal zywjz) {
		this.zywjz = zywjz;
	}
}
