package com.handge.housingfund.database.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;

// default package

/**
 * HHousingAudit generated by hbm2java
 */
@Entity
@Table(name = "c_upload_images")
@org.hibernate.annotations.Table(appliesTo = "c_upload_images", comment = "上传资料设置表")
public class CUploadImages extends Common implements java.io.Serializable {

	private static final long serialVersionUID = 3809479698222237199L;
	@Column(name = "modle", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '模块名称（01：归集 02：提取 03：贷款 04：财务）'")
	private String modle;
	@Column(name = "business", columnDefinition = "VARCHAR(2) DEFAULT NULL COMMENT '业务名称（01：单位开户 02：单位信息变更 03：单位账户注销 04：单位账号封存 05：单位账号启封 06：清册确认 07：汇缴申请 08：单位补缴 09：单位错缴 10：单位缓缴 11：单位比例调整 12：个人基数调整 13：个人账户设立 14：个人信息变更 15：账户合并转移 16：个人账户封存 17：异地转移接续（只有转出） 18：个人账户冻结 19：个人账户启封 20：个人账户解冻 01：购买住房 02：建造、翻建、大修住房 03：离休、退休 04：完全丧失劳动能力、并与单位终止劳动关系 05：户口迁出所在市、县或出境定居 06：偿还购房贷款本息（含公积金贷款） 07：房租超出家庭工资收入的规定比例 08：死亡 09：大病医疗 10：其他 01：房开公司申请 02：楼盘项目申请 03：贷款发放-申请人 04：贷款发放-共同借款人 05：贷款发放-房屋信息-购买（商品房）（期房操作流程） 06：贷款发放-房屋信息-购买（二手房）（现房操作流程） 07：贷款发放-房屋信息-自建、翻建（现房操作流程） 08：贷款发放-房屋信息-大修（现房操作流程） 09：贷款发放-担保信息 10：贷款发放 11：划拨之前 12：合同变更 13：签订合同 14：房开公司变更 15：楼盘项目变更 01：日常财务处理'")
	private String business;
	@Column(name = "certificateName", columnDefinition = "VARCHAR(255) DEFAULT NULL COMMENT '资料名称'")
	private String certificateName;
	@Column(name = "required", columnDefinition = "BIT(1) DEFAULT 0 COMMENT '是否必须（0：是 1：否）'")
	private Boolean required;

	public CUploadImages() {
		super();
	}

	public CUploadImages(String id, Date created_at, Date updated_at, Date deleted_at, boolean deleted, String modle,
			String business, String certificateName, Boolean required) {
		this.id = id;
		this.created_at = created_at;
		this.updated_at = updated_at;
		this.deleted_at = deleted_at;
		this.deleted = deleted;
		this.modle = modle;
		this.business = business;
		this.certificateName = certificateName;
		this.required = required;
	}

	public String getModle() {
		return modle;
	}

	public void setModle(String modle) {
		this.updated_at = new Date();
		this.modle = modle;
	}

	public String getBusiness() {
		return business;
	}

	public void setBusiness(String business) {
		this.updated_at = new Date();
		this.business = business;
	}

	public String getCertificateName() {
		return certificateName;
	}

	public void setCertificateName(String certificateName) {
		this.updated_at = new Date();
		this.certificateName = certificateName;
	}

	public Boolean getRequired() {
		return required;
	}

	public void setRequired(Boolean required) {
		this.updated_at = new Date();
		this.required = required;
	}
}
