
package com.handge.housingfund.others.webservice.pdfca;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISignatureServiceService", targetNamespace = "http://ws.sign.szca.com.cn/", wsdlLocation = "http://111.85.51.218:15004/szcaCertificate/services/signature?wsdl")
public class ISignatureServiceService
    extends Service
{

    private final static URL ISIGNATURESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ISIGNATURESERVICESERVICE_EXCEPTION;
    private final static QName ISIGNATURESERVICESERVICE_QNAME = new QName("http://ws.sign.szca.com.cn/", "ISignatureServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://111.85.51.218:15004/szcaCertificate/services/signature?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISIGNATURESERVICESERVICE_WSDL_LOCATION = url;
        ISIGNATURESERVICESERVICE_EXCEPTION = e;
    }

    public ISignatureServiceService() {
        super(__getWsdlLocation(), ISIGNATURESERVICESERVICE_QNAME);
    }

    public ISignatureServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISIGNATURESERVICESERVICE_QNAME, features);
    }

    public ISignatureServiceService(URL wsdlLocation) {
        super(wsdlLocation, ISIGNATURESERVICESERVICE_QNAME);
    }

    public ISignatureServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISIGNATURESERVICESERVICE_QNAME, features);
    }

    public ISignatureServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISignatureServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISignatureService
     */
    @WebEndpoint(name = "ISignatureServicePort")
    public ISignatureService getISignatureServicePort() {
        return super.getPort(new QName("http://ws.sign.szca.com.cn/", "ISignatureServicePort"), ISignatureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISignatureService
     */
    @WebEndpoint(name = "ISignatureServicePort")
    public ISignatureService getISignatureServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sign.szca.com.cn/", "ISignatureServicePort"), ISignatureService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISIGNATURESERVICESERVICE_EXCEPTION!= null) {
            throw ISIGNATURESERVICESERVICE_EXCEPTION;
        }
        return ISIGNATURESERVICESERVICE_WSDL_LOCATION;
    }

}
