
package com.handge.housingfund.others.webservice.pdfca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISignatureService", targetNamespace = "http://ws.sign.szca.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISignatureService {


    /**
     * 
     * @param base64File
     * @param fileName
     * @param stampPattern
     * @param stampType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pdfSignatureToIndex", targetNamespace = "http://ws.sign.szca.com.cn/", className = "com.handge.housingfund.others.webservice.pdfca.PdfSignatureToIndex")
    @ResponseWrapper(localName = "pdfSignatureToIndexResponse", targetNamespace = "http://ws.sign.szca.com.cn/", className = "com.handge.housingfund.others.webservice.pdfca.PdfSignatureToIndexResponse")
    public String pdfSignatureToIndex(
        @WebParam(name = "base64File", targetNamespace = "http://ws.sign.szca.com.cn/")
        String base64File,
        @WebParam(name = "fileName", targetNamespace = "http://ws.sign.szca.com.cn/")
        String fileName,
        @WebParam(name = "stampType", targetNamespace = "http://ws.sign.szca.com.cn/")
        String stampType,
        @WebParam(name = "stampPattern", targetNamespace = "http://ws.sign.szca.com.cn/")
        List<StampPattern> stampPattern);

    /**
     * 
     * @param base64File
     * @param fileName
     * @param stamps
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pdfSignature", targetNamespace = "http://ws.sign.szca.com.cn/", className = "com.handge.housingfund.others.webservice.pdfca.PdfSignature")
    @ResponseWrapper(localName = "pdfSignatureResponse", targetNamespace = "http://ws.sign.szca.com.cn/", className = "com.handge.housingfund.others.webservice.pdfca.PdfSignatureResponse")
    public String pdfSignature(
        @WebParam(name = "base64File", targetNamespace = "http://ws.sign.szca.com.cn/")
        String base64File,
        @WebParam(name = "fileName", targetNamespace = "http://ws.sign.szca.com.cn/")
        String fileName,
        @WebParam(name = "stamps", targetNamespace = "http://ws.sign.szca.com.cn/")
        List<Stamp> stamps);

}
