
package com.housingfund.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CaServiceService", targetNamespace = "http://caservice.housingfund.handge.com/", wsdlLocation = "http://172.18.20.159:20001/housingfund/services/CaService?wsdl")
public class CaServiceService
    extends Service
{

    private final static URL CASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CASERVICESERVICE_EXCEPTION;
    private final static QName CASERVICESERVICE_QNAME = new QName("http://caservice.housingfund.handge.com/", "CaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.20.159:20001/housingfund/services/CaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CASERVICESERVICE_WSDL_LOCATION = url;
        CASERVICESERVICE_EXCEPTION = e;
    }

    public CaServiceService() {
        super(__getWsdlLocation(), CASERVICESERVICE_QNAME);
    }

    public CaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CASERVICESERVICE_QNAME, features);
    }

    public CaServiceService(URL wsdlLocation) {
        super(wsdlLocation, CASERVICESERVICE_QNAME);
    }

    public CaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CASERVICESERVICE_QNAME, features);
    }

    public CaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CaService
     */
    @WebEndpoint(name = "CaServicePort")
    public CaService getCaServicePort() {
        return super.getPort(new QName("http://caservice.housingfund.handge.com/", "CaServicePort"), CaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaService
     */
    @WebEndpoint(name = "CaServicePort")
    public CaService getCaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://caservice.housingfund.handge.com/", "CaServicePort"), CaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CASERVICESERVICE_EXCEPTION!= null) {
            throw CASERVICESERVICE_EXCEPTION;
        }
        return CASERVICESERVICE_WSDL_LOCATION;
    }

}
