
package com.housingfund.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CaService", targetNamespace = "http://caservice.housingfund.handge.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.housingfund.webservice.UnitInfo
     */
    @WebMethod(operationName = "GetGJJCompanyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetGJJCompanyInfo", targetNamespace = "http://caservice.housingfund.handge.com/", className = "com.housingfund.webservice.GetGJJCompanyInfo")
    @ResponseWrapper(localName = "GetGJJCompanyInfoResponse", targetNamespace = "http://caservice.housingfund.handge.com/", className = "com.housingfund.webservice.GetGJJCompanyInfoResponse")
    @Action(input = "http://caservice.housingfund.handge.com/CaService/GetGJJCompanyInfoRequest", output = "http://caservice.housingfund.handge.com/CaService/GetGJJCompanyInfoResponse")
    public UnitInfo getGJJCompanyInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
